name: Create conda environment for notebook Python kernel
on:
  push:
    paths:
      - '.github/workflows/create-conda-envs-notebook-python.yml'
      - 'environments/notebook-base-frozen.yaml'
  pull_request:
    paths:
      - '.github/workflows/create-conda-envs-notebook-python.yml'
      - 'environments/notebook-base-frozen.yaml'
  workflow_dispatch:
jobs:
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@v4
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - name: Install base notebook environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          environment-file: environments/notebook-base-frozen.yaml
          activate-environment: notebook
          use-mamba: true
      - name: Configure CUDA
        run: |
          echo CONDA_OVERRIDE_CUDA="11.4" >> $GITHUB_ENV
          # echo XLA_FLAGS="--xla_gpu_cuda_data_dir=/opt/cuda-toolkit" >> $GITHUB_ENV
          # mkdir /opt/cuda-toolkit && chown -R jovyan /opt/cuda-toolkit
          # apt-get update
          # apt-get --yes install libxml2-dev
      - name: Install cuda-toolkit
        run: |
          mamba install -y -c tiledb/label/for-cloud -c tiledb -c fastai -c pyviz -c bokeh -c conda-forge \
            python==3.9.* \
            cudatoolkit=${CONDA_OVERRIDE_CUDA} \
            cudatoolkit-dev==${CONDA_OVERRIDE_CUDA}
      - name: Install conda packages
        run: |
          # mamba clean --yes --all
          mamba install -y -c tiledb/label/for-cloud -c tiledb -c fastai -c pyviz -c bokeh -c conda-forge \
            python==3.9.* \
            cudatoolkit=${CONDA_OVERRIDE_CUDA} \
            cudatoolkit-dev==${CONDA_OVERRIDE_CUDA} \
            numpy==1.23.* \
            setuptools \
            s3contents \
            nbgitpuller \
            bash_kernel \
            jq \
            awscli \
            vim \
            plotly \
            ipywidgets \
            ipympl \
            yarn \
            graphviz \
            pydot \
            'pandas<2' \
            pyarrow \
            numba \
            jinja2==3.0.* \
            voila==0.3.4 \
            voila-gridstack \
            jupyter-server-proxy \
            opencv-python-headless \
            pytables \
            tree \
            scikit-learn==1.* \
            scikit-misc \
            snowflake-connector-python \
            itables \
            flask \
            flask_cors \
            jupyter_bokeh==3.0.3 \
            jupyter-panel-proxy \
            ipywidgets_bokeh \
            faiss-cpu \
            hnswlib \
            bqplot \
            ipyvuetify \
            scikit-image \
            langchain \
            huggingface_hub \
            openai \
            tiktoken \
            python-dotenv \
            sentence-transformers \
            'fsspec>2022' \
            git-lfs \
            torchvision \
            pytorch==1.12.* \
            pytorch_geometric \
            torchdata==0.4.1 \
            tensorflow-datasets \
            keras-applications \
            tensorflow==2.11.* \
            'cloudpickle<3'
      - name: List packages
        run: conda list
      - name: Export frozen conda environment
        run: conda list --explicit --md5 > notebook-python-frozen.yaml
      - name: Upload frozen conda environment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: notebook-python-frozen
          path: notebook-python-frozen.yaml
          if-no-files-found: error
          retention-days: 14
