name: Create conda environment for notebook R kernel
on:
  push:
    paths:
      - '.github/workflows/create-conda-envs-notebook-r.yml'
  pull_request:
    paths:
      - '.github/workflows/create-conda-envs-notebook-r.yml'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  r:
    runs-on: ubuntu-latest
    container:
      image: jupyter/minimal-notebook:lab-3.4.5
      options: --user root
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Remove pinned dependencies from local installation
        run: rm -f "${CONDA_DIR}/conda-meta/pinned"
      - name: Create conda environment
        run: |
          mamba create -y -n r-tiledb -c conda-forge -c tiledb/label/for-cloud -c tiledb \
            cmake \
            cxx-compiler \
            r-base==4.2.* \
            r-irkernel \
            r-tidyverse \
            'r-stringi>=1.7.12' \
            r-shiny \
            r-shinybg==0.1.6 \
            r-shinyjs \
            r-shinycssloaders \
            r-shinydashboard \
            r-shinyfeedback \
            r-shinylogs \
            r-plotly \
            r-bslib \
            r-sass \
            r-htmlwidgets \
            r-arrow \
            r-remotes \
            r-xml \
            r-dplyr \
            r-purrr \
            r-jsonlite \
            r-glue \
            r-readr \
            r-crul \
            r-dt \
            r-bslib \
            r-randomcolor \
            r-biocmanager \
            r-reticulate \
            r-ini \
            r-desc \
            r-markdown \
            r-pkgload \
            r-whisker \
            r-sever \
            r-config \
            git-lfs
      - name: Export frozen conda environment
        run: conda list -n r-tiledb --explicit --md5 > environments/notebook-r-frozen.yaml
      - name: Upload frozen conda environment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: notebook-r-frozen
          path: environments/notebook-r-frozen.yaml
          if-no-files-found: error
          retention-days: 14
      - name: Install dependencies for vcf-geo
        run: |
          mamba run --no-capture-output -n r-tiledb \
            mamba install -y -c tiledb -c pwwang -c bioconda \
              r-base==4.2.* \
              bioconductor-genomeinfodbdata \
              r-annotables \
              bioconductor-genomicalignments \
              bioconductor-genomicfeatures \
              bioconductor-genomeinfodbdata \
              bioconductor-genomicranges \
              bioconductor-rtracklayer \
              bioconductor-txdb.hsapiens.ucsc.hg19.knowngene \
              bioconductor-txdb.hsapiens.ucsc.hg38.knowngene \
              bioconductor-decoupler \
              bioconductor-limma

          mamba run --no-capture-output -n r-tiledb \
            mamba install -y -c bioconda -c tiledb \
              r-base==4.2.* \
              r-matrix==1.6.1.1 \
              r-seuratobject==4.1.4 \
              r-seurat==4.1.1 \
              r-signac==1.8.* \
              bioconductor-singlecellexperiment

          mamba run --no-capture-output -n r-tiledb \
            mamba install -y -c bioconda -c tiledb \
              patch \
              r-rcppspdlog
      - name: Export frozen conda environment (vcf-geo)
        run: conda list -n r-tiledb --explicit --md5 > environments/notebook-r-vcf-geo-frozen.yaml
      - name: Upload frozen conda environment as artifact (vcf-geo)
        uses: actions/upload-artifact@v4
        with:
          name: notebook-r-vcf-geo-frozen
          path: environments/notebook-r-vcf-geo-frozen.yaml
          if-no-files-found: error
          retention-days: 14
      - name: Configure Git
        run: |
          # This is a permissions quirk due to running Git as root inside of a Docker container
          git config --global --add safe.directory $(pwd)
          git status
      - name: Push environment files to GitHub
        #if:
        run: |
          git add environments/
          git commit -m "Update conda envs for notebook R kernels"
          git push origin main
