name: Create base conda environment for notebook
on:
  push:
    paths:
      - '.github/workflows/notebook-base.yml'
  pull_request:
    paths:
      - '.github/workflows/notebook-base.yml'
  workflow_dispatch:
jobs:
  base:
    runs-on: ubuntu-latest
    container:
      image: jupyter/minimal-notebook:lab-3.4.5
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - name: Remove pinned dependencies from local installation
        run: rm -f "${CONDA_DIR}/conda-meta/pinned"
      - name: Downgrade Python version
        run: mamba install --yes python=3.9
      - name: List packages
        run: conda list
      - name: Export frozen conda environment
        run: conda list --explicit --md5 > notebook-base-frozen.yaml
      - name: Upload frozen conda environment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: notebook-base-frozen
          path: notebook-base-frozen.yaml
          if-no-files-found: error
          retention-days: 14
  commit:
    if: github.ref_name == 'main' && github.repository_owner == 'jdblischak' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: base
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download frozen conda environment
        uses: actions/download-artifact@v4
        with:
          name: notebook-base-frozen
          path: environments/
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "runneradmin@users.noreply.github.com"
      - name: Push environment files to GitHub
        run: |
          git add environments/
          git commit -m "Update base conda env for notebook" || echo "nothing to commit"
          git push origin main
